Models/feedback.cs
// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated from a template.

// Manual changes to this file may cause unexpected behavior in your application.
// Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class feedback
    {
        private TopG_clothingEntities db = new TopG_clothingEntities();

        public int feedback_id { get; set; }
        public int person_id { get; set; }
        public string feedback_desc { get; set; }
        public Nullable<System.DateTime> feedback_date { get; set; }

        public virtual person person { get; set; }

        public string GetEmailByPersonId(int id)
        {
            var person = db.people.Find(id);

            if (person == null)
                return null;
            else
                return person.person_email;

        }
    }
}

Controllers/UserHelpController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using static System.Net.Mime.MediaTypeNames;

namespace WebApplication1.Controllers

{
    public class UserHelpController : Controller
    {
        // GET: UserHelp
        private TopG_clothingEntities db = new TopG_clothingEntities();
        public ActionResult feedback()
        {
            return View(db.feedbacks.ToList());
        }
 
        public ActionResult FAQ()
        {
            return View();
        }


        public ActionResult contact()
        {
            return View();
        }




        // GET: stores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            feedback deleted_feedback = db.feedbacks.Find(id);
            if (deleted_feedback == null)
            {
                return HttpNotFound();
            }
            return View(deleted_feedback);
        }

        // POST: stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            feedback deleted_feedback = db.feedbacks.Find(id);
            db.feedbacks.Remove(deleted_feedback);
            db.SaveChanges();
            return RedirectToAction("feedback");
        }


        public string GetEmailByPersonId(int id)
        {
            var person = db.people.Find(id);

            return person.person_email;

        }

        [ActionName("Create")]

        public ActionResult Create()
        {
            return View();
        }

        // POST: stores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "feedback_id,person_id,feedback_desc,feedback_date")] feedback newfeedback)
        {
            if (ModelState.IsValid)
            {
                var x = (int)Session["Per_person"];
                DateTime y = DateTime.Now;
                newfeedback.person_id = x;
                newfeedback.feedback_date = y;
                db.feedbacks.Add(newfeedback);
                db.SaveChanges();
                return RedirectToAction("feedback");

            }

            return View(newfeedback);

        }

        [ActionName("Edit_feedback")]
        // GET: stores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            feedback editfeedback = db.feedbacks.Find(id);
            if (editfeedback == null)
            {
                return HttpNotFound();
            }
            return View(editfeedback);
        }



        // POST: stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit_feedback")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "person_id,feedback_id,feedback_desc,feedback_date")] feedback editfeedback)
        {
            if (ModelState.IsValid)
            {
                var x = (int)Session["Per_person"];
                editfeedback.person_id = x;
                DateTime y = DateTime.Now;
                editfeedback.feedback_date = y;
                db.Entry(editfeedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("feedback");
            }
            return View(editfeedback);
        }


    }
}

Views/UserHelp/Create.cshtml
@model WebApplication1.Models.feedback


@{
    ViewBag.Title = "Submit Feedback";
}


<body class="Website_body">

    <h2 style="text-align:center">Submit Feedback</h2>
    @using (Html.BeginForm("Create", "UserHelp", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group" style="text-align:center">
            @Html.TextAreaFor(model => model.feedback_desc, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.feedback_desc)
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    }

</body>

Views/UserHelp/Delete.cshtml
@model WebApplication1.Models.feedback

@{
    ViewBag.Title = "Delete";
}


<body class="Website_body">

    <h3 style="text-align:center" >Are you sure you want to delete this?</h3>
    <div style="text-align:center">
       
        <br />

        <br />

        <dl class="dl-horizontal">
            <dt style="color : red">
                @Html.DisplayNameFor(model => model.feedback_desc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.feedback_desc)
            </dd>

            <br />

            <br />

            <dt style="color : red">
                @Html.DisplayNameFor(model => model.feedback_date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.feedback_date)
            </dd>

            <br/>
            <br/>

            <dt style="color : red">
                @Html.DisplayNameFor(model => model.person.person_Fname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.person.person_Fname)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color" style="text-align:center">
                <input type="submit" value="Delete" class="btn btn-default" /> 
            </div>
        }
    </div>


</body>

Views/UserHelp/Edit_feedback.cshtml
@model WebApplication1.Models.feedback

@{
    ViewBag.Title = "Edit_feedback";

}

<body class="Website_body">
    <h2 style="text-align:center">Edit_feedback</h2>
    <br />

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <br />
            <br />
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.feedback_id)


            <br />
            <div class="form-group" style="text-align:center">
                <h3>Your previous feedback description </h3>
                <div class="col-md-10" style="text-align:center">
                    @Html.TextAreaFor(model => model.feedback_desc, new { @class = "form-control", rows = 4, cols = 40 })
                    @Html.ValidationMessageFor(model => model.feedback_desc, "", new { @class = "text-danger" })
                </div>

            </div>

            <br />
            <br />

            <div class="form-group" style="text-align:center">
                <div class="col-md-offset-2 col-md-10" style="text-align:center">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>

            <br />
        </div>
    }

  


</body>

Views/UserHelp/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
}


<body class="Website_body">
 
    <body>
        <h2 id="freqaskedheader">Frequently Asked Questions</h2>
        <article class="faq-container">


            <section class="faq-question">
                <h3>Question 1: What types of clothes do you sell?</h3>
                <p>Answer: We offer a wide range of clothes including hoodies, shirts, and sunglasses.</p>
            </section>

            <section class="faq-question">
                <h3>Question 2: How can I track my order?</h3>
                <p>Answer: Once your order is shipped, you will receive a tracking number via email to monitor your delivery.</p>
            </section>

            <section class="faq-question">
                <h3>Question 3: Can I return or exchange items?</h3>
                <p>Answer: Yes, we have a hassle-free return and exchange policy. Please check our <a href="#">Return Policy</a> for details.</p>
            </section>

            <section class="faq-question">
                <h3>Question 4: Are the clothes sustainable?</h3>
                <p>Answer: We are committed to sustainability. Our clothes are made from eco-friendly materials, and we follow ethical practices in production.</p>
            </section>

            <section class="faq-question">
                <h3>Question 5: How do I contact customer support?</h3>
                <p>Answer: You can reach our customer support team through our <a href="#">Contact Us</a> page or by emailing support@hotmail.com</p>
            </section>

            <!-- Add more FAQ sections as needed -->

        </article>

        <aside class="additional-info">
            <h2>Additional Information</h2>

            <section>
                <h3>Shipping Information:</h3>
                <p>Find details about our shipping methods, delivery times, and associated costs.</p>
            </section>

            <section>
                <h3>Size Guide:</h3>
                <p>Not sure about your size? Consult our size guide to ensure a perfect fit.</p>
            </section>

            <section>
                <h3>Latest Offers:</h3>
                <p>Check out our current promotions and special offers on selected items.</p>
            </section>
        </aside>


    </body>

Views/UserHelp/ForgetPassword.cshtml
@{
    ViewBag.Title = "ForgetPassword";
    Layout = "~/Views/shared/_LayoutLogin.cshtml";
}

<body>

    <div class="signincontainer">

        <div class="signinform">
            <h1 id="signtitle">Log in</h1>
            <h2><b>A verification code was sent to your Mail</b></h2>
            <form>
                <div>


                    <div class="input-field">
                        <i class="fa-solid fa-envelope"></i>
                        <input type="text" placeholder="Verificatoin Code" name="VerificationCode">

                    </div>


                    <div class="input-field">
                        <i class="fa-solid fa-lock"></i>
                        <input type="password" placeholder=" New password" name="password">

                    </div>


                    <div class="input-field">
                        <i class="fa-solid fa-lock"></i>
                        <input type="password" placeholder=" Re-New password" name="re-enter password">

                    </div>


                    <div class="Loginbtns">

                        <button type="button" onclick="location.href='Index.html'"><b>Submit</b></button>
                    </div>

            </form>
        </div>

</body>

Views/UserHelp/feedback.cshtml
@model IEnumerable<WebApplication1.Models.feedback>

@{
    ViewBag.Title = "Feedback Form";
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
}




<body class="Website_body">
    <table style="width: 100%; border-collapse: collapse; border: 2px solid white;">
        <tr style="border-bottom: 1px solid white;">

            <th style="padding: 10px; border-right: 1px solid white;">@Html.DisplayNameFor(model => model.feedback_id) </th>
            
            <th style="padding: 10px; border-right: 1px solid white;">Email</th>
          
            <th style="padding: 10px; border-right: 1px solid white;">@Html.DisplayNameFor(model => model.feedback_desc) </th>
            <th style="padding: 10px; border-right: 1px solid white;">@Html.DisplayNameFor(model => model.feedback_date) </th>

            @if (Model != null)
            {
                if (Session["Per_role"] == "user")
                {
                    <th colspan="2" style="padding: 10px; border-right: 1px solid white; text-align:center">Change</th>
                }
            }
        </tr>


        @if (Session["Per_role"] == "admin")
        {

            <h2 style="text-align:center">Welcome Admin</h2>
            <br />
            <h3 style="text-align:center">The feedbacks</h3>




            if (Model != null)
            {
                foreach (var item in Model)
                {

                    var mail = item.GetEmailByPersonId(item.person_id);
                    <tr style="border-bottom: 1px solid white; text-align:center">
                        <td style="padding: 10px; border-right: 1px solid white;">@Html.DisplayFor(modelItem => item.feedback_id)</td>
                        <td style="padding: 10px; border-right: 1px solid white;">@mail</td>
                        <td style="padding: 10px; border-right: 1px solid white;">@Html.DisplayFor(modelItem => item.feedback_desc)</td>
                        <td style="padding: 10px; border-right: 1px solid white;">@item.feedback_date.ToString().Substring(0, 10)</td>

                    </tr>
                    <br />
                }
            }


        }
        else
        {
            if (Model != null)
            {
                <h2 style="text-align:center">Welcome back</h2>
                <br />
                <h3 style="text-align:center">Your opinion matters to us</h3>
                <br />
                <h3 style="text-align:center">Your feedbacks</h3>
                <p>@Html.ActionLink("New Feedback", "Create", null, new { @class = "btn btn-info" })</p>

                foreach (var item in Model)
                {
                    if (Session["Per_person"] != null)
                    {
                        if (item.person_id == (int)Session["Per_person"])
                        {

        <tr style="border-bottom: 1px solid white; text-align:center">
        <td style="padding: 10px; border-right: 1px solid white; text-align: center ">@Html.DisplayFor(modelItem => item.feedback_id)</td>
        <td style="padding: 10px; border-right: 1px solid white; text-align: center">@Session["Person_mail"].ToString()</td>

        <td style="padding: 10px; border-right: 1px solid white; text-align: center">@Html.DisplayFor(modelItem => item.feedback_desc)</td>

        

        <td style="padding: 10px; border-right: 1px solid white; text-align: center">@item.feedback_date.ToString().Substring(0,10)</td>

        <td>@Html.ActionLink("Edit", "Edit_feedback", new { id = item.feedback_id }, new { @class = "btn btn-success" })</td>
        <td>@Html.ActionLink("Delete", "Delete", new { id = item.feedback_id }, new { @class = "btn btn-danger" })</td>



    </tr>
                        }
                   
                    }
                }
            }
        }
    </table>

   
</body>